# -*- coding: utf-8 -*-
"""Capitulo_de_livro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwcdFBMZYbTZFbNi7WpFi25ZxBXnjHXt
"""

!pip install pandas folium

import pandas as pd
import folium

# Lista com o nome de algumas cidades e suas coordenadas
dados = pd.DataFrame({
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
    'Lat': [-23.5505, -22.9068, -15.8267, -12.9714, -3.71722, -19.9167, -3.10194, -25.4284, -8.04756, -30.0331],
    'Long': [-46.6333, -43.1729, -47.9218, -38.5014, -38.5434, -43.9345, -60.025, -49.2733, -34.877, -51.23]
})

# Exibindo o DataFrame
print(dados)

# Criar um mapa centrado no Brasil
mapa = folium.Map(location=[-14.2350, -51.9253], zoom_start=4)

# Adicionar marcadores ao mapa para cada cidade
for index, row in dados.iterrows():
    folium.Marker(
        location=[row['Lat'], row['Long']],  # Coordenadas
        popup=row['Cidade'],  # Nome da cidade no pop-up
        icon=folium.Icon(icon='home')  # Ícone azul para os marcadores
    ).add_to(mapa)
# Definir as cores personalizadas
cor_fundo = '#ffffff'  # Cor de fundo (branco)
cor_fonte = '#0000ff'  # Cor da fonte (azul)

# Definir o estilo do título utilizando HTML
html = f"""
    <div style="
        background-color: {cor_fundo};
        color: {cor_fonte};
        font-family: Arial, sans-serif;
        padding: 25px;
        text-align: center;
        font-weight: bold;
        font-size: 18px;">
        Porto Alegre-RS
    </div>
"""
titulo = folium.Element(html)
mapa.get_root().html.add_child(titulo)

# Adicionar imagens nas laterais para o logotipo
left_logo_html = """
    <img src="https://raw.githubusercontent.com/josecacciatore89/imagens/main/cropped-logo.png" alt="Logo Esquerda" style="width:100px;height:auto;position:absolute;top:10px;left:100px;">
"""
right_logo_html = """
    <img src="https://raw.githubusercontent.com/josecacciatore89/png/main/museu.png" alt="Logo Direita" style="width:100px;height:auto;position:absolute;top:10px;right:100px;">
"""
left = folium.Element(left_logo_html)
mapa.get_root().html.add_child(left)
right = folium.Element(right_logo_html)
mapa.get_root().html.add_child(right)

# Salvar o mapa em um arquivo HTML
mapa.save("mapa_cidades_brasileiras.html")
# Exibir o mapa
mapa